import { Injectable, computed, signal } from '@angular/core';

export type AppLanguage = 'vi' | 'en';

const STORAGE_KEY = 'webcinema.language';

const translations = {
  vi: {
    header: {
      slogan: 'Ưu đãi vé xem phim - đặt nhanh, xem nhanh',
      deal: 'Giá rẻ độc quyền',
      news: 'Tin mới & ưu đãi',
      myTickets: 'Vé của tôi',
      loginRegister: 'Đăng nhập / đăng ký',
      hello: 'Xin chào,',
      viewAccount: 'Xem tài khoản',
      logout: 'Đăng xuất',
      movie: 'Phim',
      movieSub: 'Now showing',
      cinema: 'Rạp CineGo',
      cinemaSub: 'Rạp chiếu',
      member: 'Thành viên',
      memberSub: 'Tài khoản',
      cultureplex: 'Cultureplex',
      cultureplexSub: 'Góc CineGo',
      buyNow: 'Mua vé ngay',
      buyNowShort: 'MUA VÉ NGAY',
      homeAria: 'Trang chủ CineGo',
      vi: 'VN',
      en: 'EN',
      allCinemas: 'Tất Cả Các Rạp',
      specialCinemas: 'Rạp Đặc Biệt',
      threeDCinemas: 'Rạp 3D',
      accountCgv: 'Tài Khoản CineGo',
      memberBenefits: 'Quyền Lợi',
      onlineStore: 'Quầy Online',
      groupBooking: 'Thuê Rạp & Vé Nhóm',
      egift: 'CineGo eGift',
      rules: 'CineGo Rules',
      forStaff: 'Dành Cho Nhân Viên',
      forUsers: 'Dành Cho Người Dùng'
    },
    footer: {
      companyName: 'CineGo Việt Nam',
      intro: 'Giới thiệu',
      onlineUtilities: 'Tiện ích Online',
      giftCard: 'Thẻ Quà Tặng',
      careers: 'Tuyển Dụng',
      advertisingContact: 'Liên Hệ Quảng Cáo CineGo',
      partners: 'Dành cho đối tác',
      termsOfUse: 'Điều khoản sử dụng',
      generalTerms: 'Điều Khoản Chung',
      transactionTerms: 'Điều Khoản Giao Dịch',
      paymentPolicy: 'Chính Sách Thanh Toán',
      privacyPolicy: 'Chính Sách Bảo Mật',
      cinemaRules: 'Những Quy Định Tại Rạp Phim',
      faq: 'Câu Hỏi Thường Gặp',
      connectWithUs: 'Kết nối với chúng tôi',
      customerCare: 'Chăm sóc khách hàng',
      hotlineLabel: 'Hotline: 1900 0240',
      workingHours: 'Giờ làm việc: 8:00 - 22:00 (Tất cả các ngày bao gồm cả Lễ Tết)',
      supportEmail: 'Email hỗ trợ: hoidap@cinego.vn',
      legalName: 'CÔNG TY TNHH CJ CINEGO VIỆT NAM',
      businessCertificate: 'Giấy Chứng nhận đăng ký doanh nghiệp: 0979389909 đăng ký lần đầu ngày 15/04/2026, được cấp bởi Sở Kế hoạch và Đầu tư Thành phố Hà Nội',
      address: 'Địa chỉ: Số 4, đường Quang Trung, phường Hà Đông, Thành phố Hà Nội, Việt Nam',
      hotline: 'Đường dây nóng (Hotline): 1900 0240',
      copyright: 'COPYRIGHT 2026 CJ CINEGO VIETNAM CO., LTD. ALL RIGHTS RESERVED'
    },
    home: {
      ctaHub: 'Rạp CineGo',
      ctaHubSub: 'Hệ thống rạp',
      ctaMovies: 'Now Showing',
      ctaMoviesSub: 'Phim đang chiếu',
      ctaSpecial: 'CineGo Special',
      ctaSpecialSub: 'Đặc trưng CineGo',
      ctaRegister: 'Register Now',
      ctaRegisterSub: 'Đăng ký ngay',
      quickAccessTitle: 'Truy cập nhanh',
      movieSelectionTitle: 'Movie Selection',
      movieActionDetails: 'Xem chi tiết',
      movieActionBook: 'Mua vé',
      movieActionTrailer: 'Trailer',
      movieTrailerDetail: 'Chi tiết',
      movieEmptyTitle: 'Chưa có phim hiển thị',
      movieEmptyDescription: 'Lưới poster sẽ xuất hiện sau khi backend trả danh sách phim.',
      categoriesTitle: 'Danh mục CineGo',
      categoriesSubtitle: 'Phim, rạp, thành viên, cultureplex',
      nowShowingTitle: 'Phim Đang Chiếu',
      nowShowingDescription: 'Khám phá những suất chiếu mới nhất.',
      comingSoonTitle: 'Phim Sắp Chiếu',
      comingSoonDescription: 'Theo dõi lịch ra mắt và trailer mới.',
      theatersDescription: 'Danh sách rạp theo khu vực, dễ chọn nhanh.',
      breadcrumbPhim: 'Phim',
      eventBadge: 'Thành Viên CineGo | Tin Mới & Ưu Đãi',
      paymentSuccess: 'Thanh toán thành công',
      paymentCancelled: 'Hủy thanh toán thành công',
      paymentFailed: 'Thanh toán thất bại',
      informationUpdating: 'Thông tin đang được cập nhật'
    },
    admin: {
      title: 'Quản trị CineGo',
      description: 'Cấu hình rạp, phim, khuyến mãi và báo cáo.'
    },
    management: {
      menu: 'Menu',
      dashboard: 'Dashboard',
      movies: 'Phim',
      showtimes: 'Suất chiếu',
      cinemas: 'Rạp & Phòng',
      seats: 'Ghế ngồi',
      bookings: 'Đặt vé',
      invoices: 'Hóa đơn',
      foodBeverages: 'Bắp nước',
      promotions: 'Khuyến mãi',
      users: 'Người dùng',
      customers: 'Khách hàng',
      staff: 'Nhân viên',
      reports: 'Báo cáo',
      settings: 'Cài đặt',
      search: 'Tìm kiếm...',
      allAreasFilter: '-- Tất cả khu vực --',
      allCinemasFilter: '-- Tất cả rạp --',
      allRoomsFilter: '-- Tất cả phòng --',
      allStatusFilter: '-- Tất cả trạng thái --',
      devMessage: 'Tính năng đang được phát triển',
      forUsers: 'Dành cho người dùng',
      others: 'Khác',
      events: 'Sự kiện',
      banners: 'Banner',
      dashboardOverview: 'Tổng quan hệ thống',
      today: 'Hôm nay',
      revenueToday: 'Doanh thu hôm nay',
      ticketsSold: 'Vé đã bán hôm nay',
      activeMovies: 'Phim đang chiếu',
      seatOccupancy: 'Tỷ lệ lấp đầy ghế',
      revenueLast7Days: 'Doanh thu 7 ngày qua',
      topSellingMovies: 'Phim bán chạy nhất',
      viewAll: 'Xem tất cả',
      tickets: 'Vé',
      recentBookings: 'Đặt vé gần đây',
      customer: 'Khách hàng',
      movie: 'Phim',
      dateAndTime: 'Ngày & Giờ',
      total: 'Tổng cộng',
      status: 'Trạng thái',
      paid: 'Đã thanh toán',
      pending: 'Chờ thanh toán',
      cancelled: 'Đã hủy',
      foodBeverage7Days: 'Bắp nước (7 ngày)',
      totalRevenue: 'Tổng doanh thu',
      sold: 'đã bán',
      activePromotions: 'Khuyến mãi đang chạy',
      seatManagement: 'Quản lý ghế ngồi',
      seatGenerate: 'Tạo ghế',
      seatRefresh: 'Làm mới trạng thái',
      seatSearch: 'Tìm ghế, mã phòng...',
      seatLine: 'Dòng',
      seatNumber: 'Số',
      seatType: 'Loại ghế',
      seatActions: 'Hành động',
      seatAvailable: 'Trống',
      seatHeld: 'Đang giữ',
      seatOccupied: 'Đã đặt',
      seatStandard: 'Thường',
      seatVip: 'VIP',
      seatSweetBox: 'Sweet Box',
      seatScheduleCode: 'Mã lịch chiếu',
      seatViewMap: 'Xem sơ đồ',
      seatArea: 'Khu vực',
      selectArea: 'Chọn khu vực',
      cinemaLabel: 'Rạp chiếu',
      selectCinema: 'Chọn rạp',
      selectMovie: 'Chọn phim',
      selectRoom: 'Chọn phòng',
      selectRoomType: 'Chọn loại phòng',
      selectPromotionType: 'Chọn loại khuyến mãi',
      selectCustomerRank: 'Chọn hạng khách hàng',
      selectAgeRating: 'Chọn độ tuổi',
      selectBanner: 'Chọn banner',
      selectStatus: 'Chọn trạng thái',
      selectGender: 'Chọn giới tính',
      noScheduleSelected: 'Chưa chọn suất chiếu',
      selectScheduleHint: 'Chọn một suất chiếu bên trái để xem chi tiết hoặc tạo mới',
      movieSelectHint: 'Vui lòng chọn một bộ phim từ danh sách để xem chi tiết.',
      seatRoom: 'Phòng chiếu',
      seatMapTitle: 'Sơ đồ ghế',
      seatUnavailable: 'Không thể chọn',
      seatNotes: 'Ghi chú',
      noMapData: 'Chưa có sơ đồ ghế',
      noMapDataDesc: 'Vui lòng chọn phòng chiếu hoặc tạo mới ghế cho phòng này.',
      seatModalGenerateTitle: 'Tạo danh sách ghế',
      seatModalGenerateDesc: 'Thao tác này sẽ tự động tạo sơ đồ ghế chuẩn cho phòng chiếu. Những ghế cũ sẽ bị xóa hoặc ghi đè.',
      seatModalRoomName: 'Tên rạp chiếu',
      seatModalRoomCode: 'Mã phòng chiếu',
      seatModalEditTitle: 'Cập nhật ghế',
      seatModalEditDesc: 'Sửa thông tin dòng và số của ghế.',
      seatModalDeleteTitle: 'Xóa ghế ngồi?',
      seatModalDeleteDesc: 'Bạn có chắc chắn muốn xóa ghế này? Hành động này không thể hoàn tác.',
      seatModalRefreshTitle: 'Làm mới trạng thái',
      seatModalRefreshDesc: 'Hệ thống sẽ đồng bộ và cập nhật lại trạng thái ghế dựa trên các giao dịch của phòng chiếu này.',
      seatSave: 'Lưu',
      seatCancel: 'Hủy',
      seatDelete: 'Xóa',
      seatEdit: 'Sửa',
      seatSelectMultiple: 'Chọn nhiều ghế',
      seatCancelSelection: 'Hủy',
      seatRefreshSelected: 'Làm mới ghế đã chọn',
      cinemaManagement: 'Quản lý rạp & phòng chiếu',
      addCinema: 'Thêm rạp',
      addRoom: 'Thêm phòng',
      cinemaName: 'Tên rạp',
      cinemaCode: 'Mã rạp',
      address: 'Địa chỉ',
      description: 'Mô tả',
      totalRooms: 'Số phòng',
      roomType: 'Loại phòng',
      capacity: 'Sức chứa',
      roomName: 'Tên phòng (tùy chọn)',
      lastUpdated: 'Cập nhật',
      roomSettings: 'Thiết lập phòng',
      cinemaDetails: 'Chi tiết rạp',
      noCinemas: 'Không có rạp nào ở khu vực này.',
      noRooms: 'Không có phòng chiếu nào ở rạp này.',
      selectCinemaToViewRooms: 'Vui lòng chọn rạp để xem danh sách phòng.',
      searchCinemaOrRoom: 'Tìm kiếm rạp, phòng chiếu...',
      confirmDeleteCinema: 'Bạn có chắc chắn muốn xóa rạp này? Sẽ xóa tất cả phòng và ghế thuộc rạp.',
      confirmDeleteRoom: 'Bạn có chắc chắn muốn xóa phòng này? Các ghế thuộc phòng cũng sẽ bị xóa.',
      statusActive: 'Đang hoạt động',
      statusInactive: 'Dừng hoạt động',
      movieManagement: 'Quản lý phim',
      addMovie: 'Thêm phim',
      editMovie: 'Sửa phim',
      deleteMovie: 'Xóa phim',
      movieName: 'Tên phim',
      movieNameEn: 'Tên tiếng Anh',
      movieDuration: 'Thời lượng (phút)',
      premiereDate: 'Ngày khởi chiếu',
      endDate: 'Ngày kết thúc',
      director: 'Đạo diễn',
      actor: 'Diễn viên',
      language: 'Ngôn ngữ',
      subtitle: 'Phụ đề',
      trailer: 'Trailer URL',
      rate: 'Phân loại',
      banner: 'Banner',
      movieType: 'Thể loại',
      movieDescription: 'Mô tả',
      movieDescriptionEn: 'Mô tả (tiếng Anh)',
      allMovies: 'Tất cả phim',
      nowShowing: 'Đang chiếu',
      hotNowShowing: 'Đang chiếu (Hot)',
      comingSoon: 'Sắp chiếu',
      topSales: 'Top doanh thu',
      confirmDeleteMovie: 'Bạn có chắc chắn muốn xóa phim này? Thao tác này không thể hoàn tác.',

      // Invoice Management
      invoiceTitle: 'Quản lý Hóa đơn',
      invoiceList: 'Danh sách hóa đơn',
      invoiceDetail: 'Chi tiết hóa đơn',
      invoiceNoSelection: 'Chưa chọn hóa đơn',
      invoiceSelectHint: 'Chọn một hóa đơn bên trái để xem chi tiết hoặc tạo mới',
      invoiceAddBtn: 'Thêm Hóa Đơn',
      invoiceEditBtn: 'Sửa',
      invoiceDeleteBtn: 'Xóa',
      invoiceCancelBtn: 'Hủy',
      invoicePayBtn: 'Thanh toán',
      invoicePrintBtn: 'In hóa đơn',
      invoiceFilterStatus: 'Trạng thái',
      invoiceFilterAllStatus: '-- Tất cả trạng thái --',
      invoiceSearchPlaceholder: 'Tìm theo mã, khách hàng...',
      invoiceFormTitleAdd: 'Thêm hóa đơn mới',
      invoiceFormTitleEdit: 'Sửa hóa đơn',
      invoiceFormCustomer: 'Khách hàng',
      invoiceFormPromotion: 'Mã khuyến mãi',
      invoiceFormTickets: 'Vé',
      invoiceFormFoods: 'Đồ ăn',
      invoiceFormSave: 'Lưu thay đổi',
      invoiceFormCreate: 'Tạo hóa đơn',
      invoiceFormCancel: 'Hủy',
      invoiceConfirmCancelTitle: 'Hủy hóa đơn?',
      invoiceConfirmCancelDesc: 'Bạn có chắc chắn muốn hủy hóa đơn này? Thao tác này không thể hoàn tác.',
      invoiceConfirmDeleteTitle: 'Xóa hóa đơn?',
      invoiceConfirmDeleteDesc: 'Bạn có chắc chắn muốn xóa hóa đơn này? Thao tác này không thể hoàn tác.',

      // User Management
      userManagement: 'Quản lý người dùng',
      userList: 'Danh sách người dùng',
      addStaff: 'Thêm nhân viên',
      bulkDelete: 'Xóa hàng loạt',
      myProfile: 'Hồ sơ của tôi',
      userSearchPlaceholder: 'Tìm kiếm người dùng',
      filterAllRoles: 'Tất cả vai trò',
      selectRole: 'Chọn vai trò',
      roleAdmin: 'Quản trị viên',
      roleStaff: 'Nhân viên',
      roleUser: 'Khách hàng',
      colId: 'ID',
      colUsername: 'Tên tài khoản',
      colEmail: 'Email',
      colName: 'Họ tên',
      colPhone: 'Số điện thoại',
      colPoint: 'Điểm',
      colRole: 'Vai trò',
      colAddress: 'Địa chỉ',
      colActions: 'Hành động',
      actionViewDetail: 'Xem chi tiết',
      actionDelete: 'Xóa',
      actionEdit: 'Sửa',
      confirmDeleteUserTitle: 'Xóa người dùng?',
      confirmDeleteUserDesc: 'Bạn có chắc chắn muốn xóa người dùng này? Thao tác này không thể hoàn tác.',
      confirmBulkDeleteUserTitle: 'Xóa nhiều người dùng?',
      confirmBulkDeleteUserDesc: 'Bạn có chắc chắn muốn xóa các người dùng đã chọn? Thao tác này không thể hoàn tác.',
      userDetailTitle: 'Chi tiết người dùng',
      staffCreateTitle: 'Tạo tài khoản nhân viên',
      staffCreateDesc: 'Nhập thông tin để tạo tài khoản nhân viên mới trên hệ thống.',
      userFormUsername: 'Username',
      userFormEmail: 'Email',
      userFormName: 'Họ tên',
      userFormPhone: 'Số điện thoại',
      userFormPassword: 'Mật khẩu',
      userFormBirthDate: 'Ngày sinh',
      userFormGender: 'Giới tính',
      userFormPoint: 'Điểm thưởng',
      userFormSave: 'Tạo tài khoản',
      myProfileTitle: 'Hồ sơ của tôi',
      myProfileDesc: 'Cập nhật thông tin cá nhân của bạn.',
      myProfileAvatar: 'Ảnh đại diện',
      myProfileUpdate: 'Cập nhật hồ sơ',
      noUsersFound: 'Không tìm thấy người dùng nào.',
      userDeletedSuccess: 'Đã xóa người dùng thành công',
      userBulkDeletedSuccess: 'Đã xóa hàng loạt người dùng thành công',
      staffCreatedSuccess: 'Đã tạo tài khoản nhân viên thành công',
      profileUpdatedSuccess: 'Cập nhật hồ sơ thành công',
      notifications: 'Thông báo',
      allNotifications: 'Tất cả thông báo',
      markAllRead: 'Đánh dấu tất cả',
      noNotifications: 'Không có thông báo nào',
      allNotificationsRead: 'Tất cả thông báo đã được đọc',
      staffOnlyFeature: 'Tính năng này chỉ dành cho nhân viên và quản lý',
      confirmDeactivateExpired: 'Bạn có chắc chắn muốn hủy kích hoạt các suất chiếu đã hết hạn?',
      errorOccurred: 'Có lỗi xảy ra: ',
      movieInfoNotFoundToDeleteShowtime: 'Không tìm thấy thông tin phim để xóa suất chiếu. Vui lòng thử lại sau.',
      deleteError: 'Lỗi xóa: ',
      seatsRefreshedSuccess: 'Làm mới các ghế đã chọn thành công!',
      seatsRefreshError: 'Lỗi khi làm mới ghế: ',
      unknownError: 'Không rõ lỗi',
      unableToExportExcel: 'Không thể xuất Excel. Vui lòng thử lại.',
      invoiceUpdatedSuccessMock: 'Cập nhật thành công! (Dữ liệu local chưa được refresh do dùng mock)',
      invoiceCreatedSuccess: 'Tạo hóa đơn thành công! Mã: ',
      invoiceCancelledSuccess: 'Đã hủy hóa đơn thành công',
      errorPrefix: 'Lỗi: ',
      cannotCancel: 'Không thể hủy',
      invoiceDeletedSuccess: 'Đã xóa hóa đơn thành công',
      cannotDelete: 'Không thể xóa',
      paymentSuccessPrefix: 'Thanh toán thành công: ',
      errorCreatingVNPayUrl: 'Lỗi tạo URL thanh toán VNPay',

      validation: {
        required: 'Trường này là bắt buộc',
        minLength: 'Cần ít nhất {{min}} ký tự',
        maxLength: 'Tối đa {{max}} ký tự',
        invalidUrl: 'URL không hợp lệ'
      },
      promotionFood: 'Bắp nước',
      promotionTicket: 'Vé',
      rankStandard: 'Phổ thông',
      rankVip: 'VIP',
      statusSuccess: 'Thành công',
      statusPending: 'Chờ thanh toán',
      statusFailure: 'Thất bại',
      statusExpired: 'Hết hạn',
      statusPaid: 'Đã thanh toán',
      statusHold: 'Đang giữ chỗ',
      statusCancelled: 'Đã hủy',
      statusEnded: 'Kết thúc',
      statusNowShowing: 'Đang chiếu',
      statusComingSoon: 'Sắp chiếu',

      // Revenue Report
      revenueReport: 'Báo cáo doanh thu',
      revenueSubtitle: 'Phân tích doanh thu theo thời gian, rạp và phim',
      revenueFromDate: 'Từ ngày',
      revenueToDate: 'Đến ngày',
      revenueGroupBy: 'Nhóm theo',
      revenueGroupByDay: 'Ngày',
      revenueGroupByWeek: 'Tuần',
      revenueGroupByMonth: 'Tháng',
      revenueCinema: 'Rạp',
      revenueAllCinemas: 'Tất cả rạp',
      revenueSelectCinema: 'Chọn rạp',
      revenueMovie: 'Phim',
      revenueAllMovies: 'Tất cả phim',
      revenueSelectMovie: 'Chọn phim',
      revenueSearch: 'Tìm kiếm',
      revenueSearching: 'Đang tải...',
      revenueExport: 'Xuất Excel',
      revenueExporting: 'Đang xuất...',
      revenueTotalRevenue: 'Tổng doanh thu',
      revenueTicketRevenue: 'Doanh thu vé',
      revenueFoodRevenue: 'Doanh thu F&B',
      revenueTicketCount: 'Số vé bán ra',
      revenueChartTitle: 'Biểu đồ doanh thu',
      revenueChartArea: 'Vùng',
      revenueChartBar: 'Cột',
      revenueTableTitle: 'Chi tiết doanh thu',
      revenueColPeriod: 'Kỳ',
      revenueColTotal: 'Tổng doanh thu',
      revenueColTicket: 'Doanh thu vé',
      revenueColFood: 'Doanh thu F&B',
      revenueColTicketCount: 'Số vé',
      revenueTableFooter: 'Tổng cộng',
      revenueNoData: 'Không có dữ liệu',
      revenueNoDataDesc: 'Vui lòng chọn khoảng thời gian và nhấn Tìm kiếm',
      revenueError: 'Không thể tải dữ liệu',
      revenueErrorDesc: 'Có lỗi xảy ra khi kết nối đến máy chủ',
      revenueNoTableData: 'Không có dữ liệu để hiển thị',
      revenuePeriods: 'kỳ',

      // Added showtime keys
      scheduleTitle: 'Quản lý Suất chiếu',
      scheduleSearchPlaceholder: 'Tìm theo tên/mã...',
      deactivateExpiredBtn: 'Hủy suất chiếu kết thúc',
      addShowtimeBtn: 'Thêm Suất Chiếu',
      showtimeListTitle: 'Danh sách suất chiếu',
      noShowtimesFound: 'Không tìm thấy suất chiếu nào',
      theaterAndRoomInfo: 'Thông tin Rạp & Phòng',
      theaterLabel: 'Rạp chiếu',
      roomLabel: 'Phòng chiếu',
      formatLabel: 'Định dạng',
      showtimeTime: 'Thời gian chiếu',
      showtimeDate: 'Ngày chiếu',
      startTime: 'Bắt đầu',
      endTime: 'Kết thúc',
      editShowtimeTitle: 'Sửa suất chiếu',
      addShowtimeTitle: 'Thêm suất chiếu mới',
      deleteShowtimeTitle: 'Xóa suất chiếu?',
      deleteShowtimeConfirm: 'Bạn có chắc chắn muốn xóa suất chiếu này? Hành động này không thể hoàn tác.',
      scheduleCreateBtn: 'Tạo suất chiếu',

      // Added cinema keys
      roomsLabel: 'phòng',
      editCinemaTitle: 'Sửa rạp',
      cinemaCodeAutoGenerated: 'Mã rạp được hệ thống tạo tự động.',
      roomCode: 'Mã phòng',
      editRoomTitle: 'Sửa phòng chiếu',
      deleteCinemaTitle: 'Xóa rạp chiếu?',
      deleteRoomTitle: 'Xóa phòng chiếu?',

      // Added movie keys
      movieSearchPlaceholder: 'Tìm kiếm phim...',
      movieListTitle: 'Danh sách phim',
      noMoviesFound: 'Không tìm thấy phim nào.',
      movieCodeReadOnly: 'Mã phim (Read-only)',
      movieGeneralInfo: 'Thông tin chung',
      movieCastFormat: 'Đoàn làm phim & Định dạng',
      movieContent: 'Nội dung',
      paginationPage: 'Trang',

      // Added promotion keys
      addPromotion: 'Thêm khuyến mãi',
      addPromotionTitle: 'Thêm khuyến mãi mới',
      colPromoProgram: 'Chương trình',
      colPromoDiscount: 'Giảm giá',
      colPromoQuantity: 'Số lượng',
      colPromoPeriod: 'Thời gian áp dụng',
      colPromoTarget: 'Đối tượng',
      colPromoStatus: 'Trạng thái',
      colPromoActions: 'Thao tác',
      noPromotionsFound: 'Không tìm thấy khuyến mãi nào',
      promoStatusRunning: 'Đang chạy',
      promoStatusEnded: 'Kết thúc',
      promoFormName: 'Tên khuyến mãi',
      promoFormType: 'Loại khuyến mãi',
      promoFormDiscount: 'Phần trăm giảm (%)',
      promoFormQuantity: 'Số lượng mã',
      promoFormRank: 'Hạng khách hàng',
      promoFormStart: 'Bắt đầu từ',
      promoFormEnd: 'Kết thúc lúc',
      promoFormDesc: 'Mô tả chương trình',
      promoFormDescPlaceholder: 'Mô tả ngắn gọn về khuyến mãi...',
      promoCreateBtn: 'Tạo mã ngay',
      promoDeleteConfirmTitle: 'Xóa khuyến mãi?',
      promoDeleteConfirmDesc: 'Bạn có chắc muốn xóa khuyến mãi này? Mã này sẽ không còn hiệu lực.',
      promoDeleteBtn: 'Xóa ngay',

      // Added event keys
      addEvent: 'Thêm sự kiện',
      addEventTitle: 'Thêm sự kiện mới',
      noEventsFound: 'Không tìm thấy sự kiện nào',
      eventStatusActive: 'Đang diễn ra',
      eventStatusEnded: 'Kết thúc',
      eventFormImage: 'Hình ảnh sự kiện',
      eventFormImageHint: 'Nhấn để tải lên hình ảnh sự kiện',
      eventFormName: 'Tên sự kiện',
      eventFormNamePlaceholder: 'Nhập tên sự kiện...',
      eventSaveBtn: 'Lưu sự kiện',
      eventDeleteConfirmTitle: 'Xóa sự kiện?',
      eventDeleteConfirmDesc: 'Bạn có chắc chắn muốn xóa sự kiện này? Hành động này không thể hoàn tác.',

      // Added banner keys
      addBanner: 'Thêm banner',
      addBannerTitle: 'Thêm banner mới',
      noBannersFound: 'Không tìm thấy banner nào',
      bannerFormImage: 'Hình ảnh Banner (Tỷ lệ 21:9 khuyên dùng)',
      bannerFormImageHint: 'Nhấn để tải lên banner',
      bannerFormTitleVi: 'Tiêu đề (Tiếng Việt)',
      bannerFormTitleEn: 'Tiêu đề (Tiếng Anh)',
      bannerSaveBtn: 'Lưu banner',
      bannerDeleteConfirmTitle: 'Xóa banner?',
      bannerDeleteConfirmDesc: 'Bạn có chắc chắn muốn xóa banner này? Hành động này không thể hoàn tác.',

      // Added setting keys
      settingsTitle: 'Cài đặt hệ thống',
      operatingRules: 'Quy tắc hoạt động',
      openTime: 'Giờ mở cửa',
      businessHours: 'Giờ hoạt động',
      closeTime: 'Giờ đóng cửa',
      closeTimeTooltip: 'Tính năng tự động khóa khi hết giờ hoạt động.',
      breakTime: 'Thời gian nghỉ giữa các suất chiếu (phút)',
      weekendPercent: 'Phụ thu cuối tuần (%)',
      timeBeginToChange: 'Thời gian khóa thay đổi lịch chiếu trước giờ chiếu (phút)',
      saveRules: 'Lưu quy tắc',
      updateRules: 'Cập nhật quy tắc',
      resetForm: 'Đặt lại',
      historyTitle: 'Lịch sử thay đổi quy tắc',
      records: 'bản ghi',
      fetchingRecords: 'Đang tải bản ghi...',
      noRecords: 'Không có bản ghi nào',
      colOpenTime: 'Giờ mở cửa',
      colOperatingHours: 'Giờ hoạt động',
      colCloseTime: 'Giờ đóng cửa',
      colBreakTime: 'Thời gian nghỉ',
      colWeekendSurcharge: 'Phụ thu cuối tuần',
      colLockChangeTime: 'Thời gian khóa thay đổi',
      unitHour: 'giờ',
      unitMinute: 'phút',
      editBtn: 'Sửa',
      deleteBtn: 'Xóa',
      toastSaveSuccess: 'Lưu quy tắc thành công',
      toastSaveError: 'Lỗi khi lưu quy tắc',
      toastUpdateSuccess: 'Cập nhật quy tắc thành công',
      toastUpdateError: 'Lỗi khi cập nhật quy tắc',
      toastDeleteSuccess: 'Xóa quy tắc thành công',
      toastDeleteError: 'Lỗi khi xóa quy tắc',
      validationBreakTimeRequired: 'Thời gian nghỉ là bắt buộc.',
      validationBreakTimeNegative: 'Thời gian nghỉ không được âm.',
      validationBreakTimeTooLong: 'Thời gian nghỉ không thể vượt quá 120 phút.',
      validationOpenHoursRange: 'Giờ hoạt động phải nằm trong khoảng từ 1 đến 24 giờ.',
      validationOpenTimeRequired: 'Giờ mở cửa là bắt buộc.',
      validationSurchargeRange: 'Phụ thu cuối tuần phải nằm trong khoảng từ 0% đến 100%.',
      settingsDeleteTitle: 'Xóa cấu hình?',
      settingsDeleteConfirm: 'Bạn có chắc chắn muốn xóa cấu hình này? Lịch sử rạp có thể bị ảnh hưởng.',

      // Added generic notification and seat extra keys
      loadingGeneric: 'Đang tải...',
      seatRefreshNote: 'Lưu ý: Chỉ làm mới khi trạng thái ghế bị treo'
    },
    movies: {
      title: 'Phim CineGo',
      description: 'Danh sách phim đang chiếu và sắp chiếu.',
      genre: 'Thể loại',
      duration: 'Thời lượng',
      releaseDate: 'Khởi chiếu',
      director: 'Đạo diễn',
      actor: 'Diễn viên',
      language: 'Ngôn ngữ',
      rated: 'Rated',
      contentTitle: 'Nội Dung Phim',
      showing: 'Phim Đang Chiếu',
      coming: 'Phim Sắp Chiếu',
      minutes: 'phút',
      preBook: 'ĐẶT TRƯỚC',
      notFound: 'Không tìm thấy thông tin phim.',
      goBack: 'Quay lại',
      noShowing: 'Hiện chưa có thông tin về các phim đang chiếu',
      noComing: 'Hiện chưa có thông tin về các phim sắp chiếu'
    },
    booking: {
      title: 'Đặt vé CineGo',
      description: 'Chọn suất chiếu, ghế ngồi và thanh toán nhanh.',
      chooseDate: 'Chọn ngày',
      chooseCity: 'Tất cả khu vực',
      chooseCinema: 'Tất cả rạp',
      noShowtimes: 'Xin lỗi, không có suất chiếu vào ngày này, hãy chọn một ngày khác.',
      selectShowtime: 'Vui lòng chọn ngày để xem lịch chiếu.',
      loadingSchedule: 'Đang tải thông tin...',
      cityHcm: 'Hồ Chí Minh',
      cityHn: 'Hà Nội',
      cityDn: 'Đà Nẵng',
      roomStandard: '2D Phụ Đề Việt',
      roomImax: 'IMAX 2D Phụ Đề Việt',
      cinemaLabel: 'Rạp',
      personSeat: 'Người / Ghế',
      screen: 'SCREEN',
      legendSelected: 'Đã chọn',
      legendBooked: 'Đã đặt',
      legendUnavailable: 'Không thể chọn',
      legendStandard: 'Thường',
      legendVip: 'VIP',
      legendSweetbox: 'Sweet Box',
      showtime: 'Suất chiếu',
      roomLabel: 'Phòng chiếu',
      movieLabel: 'Tên phim',
      seatLabel: 'Ghế',
      totalLabel: 'Tổng',
      selectSameSeatType: 'Vui lòng chọn tất cả ghế cùng loại',
      maxSeatsLimit: 'Bạn chỉ có thể chọn tối đa 8 ghế.',
      seatGapWarning: 'Vui lòng không chừa 1 ghế trống bên trái hoặc bên phải của các ghế bạn đã chọn.',
      holdSeatsError: 'Lỗi khi giữ ghế',
      holdSeatsConnectionError: 'Lỗi kết nối khi giữ ghế',
      cannotRetrievePaymentLink: 'Không lấy được link thanh toán',
      paymentProcessingError: 'Lỗi xử lý thanh toán',
      seatHoldExpired: 'Thời gian giữ ghế đã hết. Vui lòng chọn lại ghế'
    },
    shared: {
      loading: 'Đang tải',
      website: 'Website',
      close: 'Đóng',
      pleaseSelect: 'Vui lòng chọn...',
      noData: 'Không có dữ liệu'
    },
    auth: {
      loginTab: 'Đăng nhập',
      registerTab: 'Đăng ký',
      username: 'Tên đăng nhập',
      password: 'Mật khẩu',
      emailOrPhone: 'Tên đăng nhập',
      captchaPrompt: 'Vui lòng nhập ký tự bên dưới *',
      captchaInput: 'Nhập captcha',
      loadingCaptcha: 'Đang tải captcha...',
      noCaptcha: 'Không có captcha',
      forgotPassword: 'Bạn muốn tìm lại mật khẩu?',
      loginButton: 'ĐĂNG NHẬP',
      registerButton: 'ĐĂNG KÝ',
      name: 'Tên',
      phoneNumber: 'Số điện thoại',
      email: 'Email',
      birthDate: 'Ngày sinh',
      gender: 'Giới tính',
      day: 'Ngày',
      month: 'Tháng',
      year: 'Năm',
      male: 'Nam',
      female: 'Nữ',
      termsTitle: 'Điều khoản đăng ký',
      terms1: 'Bằng việc bấm nút “Đăng Ký” bên dưới. Tôi đồng ý cho phép CG Việt Nam thực hiện xử lý dữ liệu cá nhân của tôi phù hợp với mục đích mà CG Việt Nam đã thông báo tại',
      terms2: 'Thông tin cá nhân cung cấp tại đây là chính xác và trùng khớp với thông tin tại CMND/CCCD/Thẻ Căn cước và/hoặc Giấy khai sinh (Giấy tờ tuỳ thân). Email cung cấp tại đây là chính xác và thuộc quyền quản lý duy nhất của tôi.',
      terms3: 'Xác nhận email chính xác và ngày sinh khớp với thông tin trên CMND/CCCD. Nếu không trùng khớp, các thông tin này sẽ không được hỗ trợ cập nhật thay đổi và có thể không được hưởng các',
      terms4: 'Tôi đồng ý với',
      privacyPolicy: 'Chính Sách Bảo Mật',
      memberBenefits: 'Quyền lợi thành viên',
      termsOfUse: 'Điều Khoản Sử Dụng Của CG',
      requiredName: 'Vui lòng nhập tên',
      requiredUsername: 'Vui lòng nhập tên đăng nhập',
      requiredPhone: 'Vui lòng nhập số điện thoại',
      requiredEmail: 'Vui lòng nhập email',
      invalidEmail: 'Email không hợp lệ',
      requiredPassword: 'Mật khẩu tối thiểu 6 ký tự',
      requiredBirthDate: 'Vui lòng chọn ngày sinh',
      requiredGender: 'Vui lòng chọn giới tính',
      requiredCaptcha: 'Captcha là bắt buộc',
      usernameLengthError: 'Username từ 3-20 ký tự.',
      nameLengthError: 'Họ tên từ 3-20 ký tự.',
      phoneLengthError: 'SĐT phải bắt đầu bằng 0 và có 10 chữ số.',
      passwordComplexError: 'Mật khẩu cần 8-20 ký tự, có chữ hoa, chữ thường, số và ký tự đặc biệt.',
      captchaRequiredError: 'Vui lòng nhập captcha.',
      consentPrompt: 'Vui lòng đánh dấu xác nhận thông tin và đồng ý với Điều khoản Sử dụng của CG',
      consentLine: 'Bạn phải tích vào dòng này để tiếp tục.',
      registerSuccess: 'Đăng ký thành công. Vui lòng đăng nhập.',
      loginSuccessPrefix: 'Đăng nhập thành công, chào ',
      loginSuccess: 'Đăng nhập thành công',
      loginError: 'Đăng nhập không thành công',
      registerError: 'Đăng ký không thành công',
      captchaError: 'Không tải được captcha',
      captchaReload: 'Vui lòng tải lại captcha.',
      staffOnly: 'Chỉ nhân viên và quản lý được đăng nhập tại đây',
      staffMode: 'Dành cho nhân viên',
      forgotPasswordTitle: 'Tìm lại mật khẩu',
      resetPasswordTitle: 'Đổi mật khẩu',
      otpLabel: 'Nhập mã OTP',
      newPassword: 'Mật khẩu mới',
      confirmNewPassword: 'Xác nhận mật khẩu mới',
      otpSentMessage: 'Mã OTP đã được gửi đến email của bạn. Trường hợp không có vui lòng kiểm tra thư mục spam hoặc thùng rác.',
      forgotPasswordButton: 'GỬI YÊU CẦU',
      resetPasswordButton: 'ĐỔI MẬT KHẨU',
      backToLogin: 'Quay lại đăng nhập',
      forgotPasswordError: 'Không thể gửi yêu cầu tìm lại mật khẩu',
      resetPasswordError: 'Đổi mật khẩu không thành công',
      passwordMismatch: 'Mật khẩu xác nhận không khớp',
      resetPasswordSuccess: 'Đổi mật khẩu thành công. Vui lòng đăng nhập lại.',
      requiredOtp: 'Bắt buộc nhập OTP'
    },
    account: {
      title: 'Thông tin tài khoản',
      memberStatus: 'Thành viên CineGo',
      myTickets: 'Vé của tôi',
      overviewTitle: 'Thông tin chung',
      usernameLabel: 'Tên đăng nhập',
      loginStateLabel: 'Trạng thái',
      loggedIn: 'Đang đăng nhập',
      quickActionLabel: 'Chức năng nhanh',
      quickActionValue: 'Xem tài khoản và quản lý đăng xuất',
      sidebarTitle: 'Tài khoản CineGo',
      infoGeneral: 'Thông tin chung',
      details: 'Chi tiết tài khoản',
      paymentSettings: 'Cài đặt mã thanh toán',
      memberCard: 'Thẻ thành viên',
      rewardPoints: 'Điểm thưởng',
      giftCards: 'Thẻ quà tặng',
      voucher: 'VOUCHER',
      coupon: 'COUPON',
      history: 'Lịch sử giao dịch',
      hello: 'Xin chào',
      manageIntro: 'Với trang này, bạn sẽ quản lý được tất cả thông tin tài khoản của mình.',
      tierLabel: 'Cấp Độ Thẻ',
      totalSpend: 'Tổng Chi Tiêu',
      cgvPoints: 'Điểm CineGo',
      giftCardLabel: 'Thẻ quà tặng',
      view: 'Xem',
      contactInfo: 'Thông tin tài khoản',
      contactHeader: 'LIÊN HỆ',
      change: 'Thay đổi',
      cropAvatarTitle: 'Căn chỉnh ảnh đại diện',
      apply: 'Áp dụng',
      cancel: 'Hủy',
      nameLabel: 'Tên :',
      emailLabel: 'Email :',
      phoneLabel: 'Điện thoại :',
      devMessage: 'Tính năng đang được phát triển. Vui lòng quay lại sau!',
      movieName: 'TÊN PHIM',
      photoTicket: 'PHOTOTICKET',
      onlineStore: 'QUẦY ONLINE',
      egift: 'CINEGO EGIFT',
      productsCount: '{{count}} Sản phẩm',
      displayLabel: 'HIỂN THỊ:',
      bookingCode: 'Mã Đặt Vé :',
      statusLabel: 'Trạng thái :',
      statusCompleted: 'Hoàn Tất',
      fromLabel: 'From',
      toLabel: 'To',
      totalAmount: 'đ',
      changeInfoTitle: 'THAY ĐỔI THÔNG TIN',
      cityLabel: 'Thành phố/Tỉnh',
      districtLabel: 'Quận',
      addressLabel: 'Địa chỉ',
      oldPasswordLabel: 'Mật khẩu cũ',
      changePasswordToggle: 'Tôi muốn thay đổi mật khẩu',
      optionalInfoTitle: 'Thông Tin Tùy Chọn',
      cardNumberLabel: 'Số thẻ thành viên',
      favTheaterLabel: 'Rạp yêu thích',
      saveButton: 'LƯU LẠI',
      requiredHint: '* Thông tin bắt buộc',
      errorUpdatingPassword: 'Lỗi cập nhật mật khẩu',
      newPasswordMismatch: 'Mật khẩu mới và Nhập lại mật khẩu không khớp',
      couponManageTitle: 'Quản lý Coupon',
      couponRegisterTitle: 'Đăng Ký Coupon',
      couponCodeLabel: 'Số Coupon',
      registerBtn: 'ĐĂNG KÝ',
      myCouponsTitle: 'Coupon Của Bạn',
      quickSearch: 'Tìm nhanh',
      oneWeek: '1 Tuần',
      oneMonth: '1 Tháng',
      threeMonths: '3 Tháng',
      searchBtn: 'Tìm kiếm',
      movieNameBtn: 'Tên Phim',
      popcornDrinkBtn: 'Bắp Nước',
      allOption: 'Tất cả',
      unusedOption: 'Chưa sử dụng',
      usedOption: 'Đã sử dụng',
      expiredOption: 'Hết hạn',
      colCoupon: 'Coupon',
      colCouponCode: 'Số Coupon',
      colRegDate: 'Ngày đăng ký',
      colExpDate: 'Hạn sử dụng',
      colStatus: 'Trạng thái',
      badgeTicket: 'Vé',
      badgeFnB: 'F&B',
      noCouponData: 'Không có dữ liệu coupon nào khớp với bộ lọc.'
    },
    titles: {
      home: 'CineGo Cinemas Vietnam',
      login: 'Đăng nhập',
      register: 'Đăng ký tài khoản',
      movieDetail: 'Thông tin - Lịch chiếu',
      bookingTicket: 'Mua vé',
      bookingCorn: 'Bắp nước',
      bookingPayment: 'Thanh toán',
      moviesShowing: 'Phim đang chiếu',
      moviesComing: 'Phim sắp chiếu',
      forgotpassword: 'Tìm lại mật khẩu',
      changepassword: 'Đổi mật khẩu'
    },
    chatbot: {
      assistant: 'Trợ lý CineGo',
      online: 'Trực tuyến',
      placeholder: 'Nhập tin nhắn của bạn...',
      welcome: 'Xin chào! Tôi là CineGo Assistant. Tôi có thể giúp gì cho bạn?',
      promoLabel: '🎁 Khuyến mãi',
      faqLabel: '💡 Hỏi đáp FAQ',
      faqIntro: 'Bạn có thể tìm thấy câu trả lời cho các vấn đề thường gặp tại đây:',
      promoQuery: 'Hiện tại có những chương trình khuyến mãi nào?',
      systemError: 'Tôi chưa nhận được câu trả lời từ hệ thống.',
      networkError: 'Đã xảy ra lỗi kết nối với máy chủ của chatbot. Vui lòng thử lại sau!',
      refundPolicyLabel: 'Chính sách hoàn vé',
      refundPolicyDesc: 'CineGo hỗ trợ hoàn/hủy vé trước giờ chiếu ít nhất 60 phút. Số tiền hoàn sẽ được chuyển về điểm tích lũy thành viên hoặc tài khoản thanh toán ban đầu của bạn.',
      paymentMethodsLabel: 'Phương thức thanh toán',
      paymentMethodsDesc: 'Chúng tôi hỗ trợ đa dạng phương thức thanh toán: Thẻ quốc tế (Visa/Mastercard), các ví điện tử phổ biến (Momo, ZaloPay, ShopeePay), cổng thanh toán VNPAY và chuyển khoản ngân hàng.',
      membershipLabel: 'Quyền lợi thành viên',
      membershipDesc: 'Thành viên CineGo được hưởng các đặc quyền: Tích lũy điểm thưởng từ 5-10% cho mỗi giao dịch, đổi vé/bắp nước miễn phí, nhận vé sinh nhật và ưu đãi đặc quyền cho các suất chiếu sớm.',
      locationsLabel: 'Địa điểm rạp',
      locationsDesc: 'Hệ thống rạp CineGo hiện đã có mặt tại các vị trí đắc địa ở TP.HCM, Hà Nội và Đà Nẵng. Bạn có thể xem danh sách địa chỉ chi tiết tại mục "Hệ Thống Rạp" trên thanh menu chính của trang web nhé!',
      bookNow: 'Đặt vé ngay',
      bookingId: 'MÃ ĐẶT VÉ',
      confirmed: 'Đã xác nhận'
    }
  },
  en: {
    header: {
      slogan: 'Movie ticket deals - book fast, watch fast',
      deal: 'Exclusive low price',
      news: 'News & offers',
      myTickets: 'My tickets',
      loginRegister: 'Login / Register',
      hello: 'Hello,',
      viewAccount: 'View account',
      logout: 'Logout',
      movie: 'Movies',
      movieSub: 'Now showing',
      cinema: 'CineGo theaters',
      cinemaSub: 'Cinema',
      member: 'Members',
      memberSub: 'Account',
      cultureplex: 'Cultureplex',
      cultureplexSub: 'CineGo corner',
      buyNow: 'Buy tickets now',
      buyNowShort: 'TICKETS',
      homeAria: 'CineGo home',
      vi: 'VN',
      en: 'EN',
      allCinemas: 'All Cinemas',
      specialCinemas: 'Special Cinemas',
      threeDCinemas: '3D Cinemas',
      accountCgv: 'CineGo Account',
      memberBenefits: 'Benefits',
      onlineStore: 'Online Store',
      groupBooking: 'Group Booking & Rental',
      egift: 'CineGo eGift',
      rules: 'CineGo Rules',
      forStaff: 'For Staff',
      forUsers: 'For Users'
    },
    footer: {
      companyName: 'CineGo Vietnam',
      intro: 'Introduction',
      onlineUtilities: 'Online utilities',
      giftCard: 'Gift card',
      careers: 'Careers',
      advertisingContact: 'CineGo advertising contact',
      partners: 'For partners',
      termsOfUse: 'Terms of use',
      generalTerms: 'General terms',
      transactionTerms: 'Transaction terms',
      paymentPolicy: 'Payment policy',
      privacyPolicy: 'Privacy policy',
      cinemaRules: 'Cinema rules',
      faq: 'Frequently asked questions',
      connectWithUs: 'Connect with us',
      customerCare: 'Customer care',
      hotlineLabel: 'Hotline: 1900 0240',
      workingHours: 'Working hours: 8:00 - 22:00 (All days including holidays)',
      supportEmail: 'Support email: hoidap@cinego.vn',
      legalName: 'CJ CINEGO VIETNAM CO., LTD.',
      businessCertificate: 'Business registration certificate: 0979389909 first registered on 15/04/2026, issued by the Hanoi Department of Planning and Investment',
      address: 'Address: No. 4 Quang Trung Street, Ha Dong Ward, Hanoi, Vietnam',
      hotline: 'Hotline: 1900 0240',
      copyright: 'COPYRIGHT 2026 CJ CINEGO VIETNAM CO., LTD. ALL RIGHTS RESERVED'
    },
    home: {
      ctaHub: 'CineGo theaters',
      ctaHubSub: 'Theater system',
      ctaMovies: 'Now Showing',
      ctaMoviesSub: 'Now playing',
      ctaSpecial: 'CineGo Special',
      ctaSpecialSub: 'CineGo signature',
      ctaRegister: 'Register Now',
      ctaRegisterSub: 'Sign up now',
      quickAccessTitle: 'Quick access',
      movieSelectionTitle: 'Movie selection',
      movieActionDetails: 'View details',
      movieActionBook: 'Booking',
      movieActionTrailer: 'Trailer',
      movieTrailerDetail: 'Description',
      movieEmptyTitle: 'No movies available yet',
      movieEmptyDescription: 'The poster grid will appear after the backend returns the movie list.',
      categoriesTitle: 'CineGo categories',
      categoriesSubtitle: 'Movies, theaters, members, cultureplex',
      nowShowingTitle: 'Now showing',
      nowShowingDescription: 'Explore the latest screening slots.',
      comingSoonTitle: 'Coming soon',
      comingSoonDescription: 'Track release dates and new trailers.',
      theatersDescription: 'Theater list by region, easy to choose quickly.',
      breadcrumbPhim: 'Movies',
      eventBadge: 'CineGo Member | News & Offers',
      paymentSuccess: 'Payment successful',
      paymentCancelled: 'Payment cancelled successfully',
      paymentFailed: 'Payment failed',
      informationUpdating: 'Information is being updated'
    },
    admin: {
      title: 'CineGo Admin',
      description: 'Configure theaters, movies, promotions, and reports.'
    },
    management: {
      menu: 'Menu',
      dashboard: 'Dashboard',
      movies: 'Movies',
      showtimes: 'Showtimes',
      cinemas: 'Cinemas & Rooms',
      seats: 'Seats',
      bookings: 'Bookings',
      invoices: 'Invoices',
      foodBeverages: 'Food & Beverages',
      promotions: 'Promotions',
      users: 'Users',
      customers: 'Customers',
      staff: 'Staff',
      reports: 'Reports',
      settings: 'Settings',
      search: 'Search...',
      allAreasFilter: '-- All Areas --',
      allCinemasFilter: '-- All Cinemas --',
      allRoomsFilter: '-- All Rooms --',
      allStatusFilter: '-- All Statuses --',
      devMessage: 'Feature is under development',
      forUsers: 'For Users',
      others: 'Others',
      events: 'Events',
      banners: 'Banner',
      dashboardOverview: 'Dashboard Overview',
      today: 'Today',
      revenueToday: 'Revenue Today',
      ticketsSold: 'Tickets Sold Today',
      activeMovies: 'Active Movies',
      seatOccupancy: 'Seat Occupancy',
      revenueLast7Days: 'Revenue Last 7 Days',
      topSellingMovies: 'Top Selling Movies',
      viewAll: 'View All',
      tickets: 'Tickets',
      recentBookings: 'Recent Bookings',
      customer: 'Customer',
      movie: 'Movie',
      dateAndTime: 'Date & Time',
      total: 'Total',
      status: 'Status',
      paid: 'Paid',
      pending: 'Pending',
      cancelled: 'Cancelled',
      foodBeverage7Days: 'Food & Beverage (7 Days)',
      totalRevenue: 'Total Revenue',
      sold: 'sold',
      activePromotions: 'Active Promotions',
      seatManagement: 'Seat Management',
      seatGenerate: 'Generate Seats',
      seatRefresh: 'Refresh Status',
      seatSearch: 'Search seat, room...',
      seatLine: 'Row',
      seatNumber: 'Number',
      seatType: 'Type',
      seatActions: 'Actions',
      seatAvailable: 'Available',
      seatHeld: 'Held',
      seatOccupied: 'Occupied',
      seatStandard: 'Standard',
      seatVip: 'VIP',
      seatSweetBox: 'Sweet Box',
      seatScheduleCode: 'Schedule Code',
      seatViewMap: 'View Map',
      seatArea: 'Area',
      selectArea: 'Select Area',
      cinemaLabel: 'Cinema',
      selectCinema: 'Select Cinema',
      selectMovie: 'Select Movie',
      selectRoom: 'Select Room',
      selectRoomType: 'Select Room Type',
      selectPromotionType: 'Select Promotion Type',
      selectCustomerRank: 'Select Customer Rank',
      selectAgeRating: 'Select Age Rating',
      selectBanner: 'Select Banner',
      selectStatus: 'Select Status',
      selectGender: 'Select Gender',
      noScheduleSelected: 'No showtime selected',
      selectScheduleHint: 'Select a showtime on the left to view details or create new',
      movieSelectHint: 'Please select a movie from the list to view details.',
      seatRoom: 'Room',
      seatMapTitle: 'Seat Map',
      seatUnavailable: 'Unavailable',
      seatNotes: 'Notes',
      noMapData: 'No seat map yet',
      noMapDataDesc: 'Please select a room or generate new seats for this room.',
      seatModalGenerateTitle: 'Generate Seat List',
      seatModalGenerateDesc: 'This will automatically generate a standard seat map. Old seats will be deleted or overwritten.',
      seatModalRoomName: 'Cinema Name',
      seatModalRoomCode: 'Room Code',
      seatModalEditTitle: 'Edit Seat',
      seatModalEditDesc: 'Edit the row and number of the seat.',
      seatModalDeleteTitle: 'Delete Seat?',
      seatModalDeleteDesc: 'Are you sure you want to delete this seat? This action cannot be undone.',
      seatModalRefreshTitle: 'Refresh Status',
      seatModalRefreshDesc: 'The system will synchronize and update seat statuses based on the latest transactions for this room.',
      seatSave: 'Save',
      seatCancel: 'Cancel',
      seatDelete: 'Delete',
      seatEdit: 'Edit',
      seatSelectMultiple: 'Select Multiple',
      seatCancelSelection: 'Cancel',
      seatRefreshSelected: 'Refresh Selected',
      cinemaManagement: 'Cinema & Room Management',
      addCinema: 'Add Cinema',
      addRoom: 'Add Room',
      cinemaName: 'Cinema Name',
      cinemaCode: 'Cinema Code',
      address: 'Address',
      description: 'Description',
      totalRooms: 'Total Rooms',
      roomType: 'Room Type',
      capacity: 'Capacity',
      roomName: 'Room Name (optional)',
      lastUpdated: 'Last Updated',
      roomSettings: 'Room Settings',
      cinemaDetails: 'Cinema Details',
      noCinemas: 'No cinemas found in this area.',
      noRooms: 'No screening rooms in this cinema.',
      selectCinemaToViewRooms: 'Please select a cinema to view its rooms.',
      searchCinemaOrRoom: 'Search cinema, room...',
      confirmDeleteCinema: 'Are you sure you want to delete this cinema? All rooms and seats will be deleted.',
      confirmDeleteRoom: 'Are you sure you want to delete this room? All seats will be deleted.',
      statusActive: 'Active',
      statusInactive: 'Inactive',
      movieManagement: 'Movie Management',
      addMovie: 'Add Movie',
      editMovie: 'Edit Movie',
      deleteMovie: 'Delete Movie',
      movieName: 'Movie Name',
      movieNameEn: 'English Name',
      movieDuration: 'Duration (mins)',
      premiereDate: 'Premiere Date',
      endDate: 'End Date',
      director: 'Director',
      actor: 'Actors',
      language: 'Language',
      subtitle: 'Subtitle',
      trailer: 'Trailer URL',
      rate: 'Rate',
      banner: 'Banner',
      movieType: 'Movie Type',
      movieDescription: 'Description',
      movieDescriptionEn: 'English Description',
      allMovies: 'All Movies',
      nowShowing: 'Now Showing',
      hotNowShowing: 'Now Showing (Hot)',
      comingSoon: 'Coming Soon',
      topSales: 'Top Sales',
      confirmDeleteMovie: 'Are you sure you want to delete this movie? This action cannot be undone.',

      // Invoice Management
      invoiceTitle: 'Invoice Management',
      invoiceList: 'Invoice List',
      invoiceDetail: 'Invoice Details',
      invoiceNoSelection: 'No invoice selected',
      invoiceSelectHint: 'Select an invoice on the left to view details or create a new one',
      invoiceAddBtn: 'Add Invoice',
      invoiceEditBtn: 'Edit',
      invoiceDeleteBtn: 'Delete',
      invoiceCancelBtn: 'Cancel',
      invoicePayBtn: 'Pay Now',
      invoicePrintBtn: 'Print',
      invoiceFilterStatus: 'Status',
      invoiceFilterAllStatus: '-- All statuses --',
      invoiceSearchPlaceholder: 'Search by code, customer...',
      invoiceFormTitleAdd: 'Add New Invoice',
      invoiceFormTitleEdit: 'Edit Invoice',
      invoiceFormCustomer: 'Customer',
      invoiceFormPromotion: 'Promotion Code',
      invoiceFormTickets: 'Tickets',
      invoiceFormFoods: 'Foods',
      invoiceFormSave: 'Save Changes',
      invoiceFormCreate: 'Create Invoice',
      invoiceFormCancel: 'Cancel',
      invoiceConfirmCancelTitle: 'Cancel Invoice?',
      invoiceConfirmCancelDesc: 'Are you sure you want to cancel this invoice? This action cannot be undone.',
      invoiceConfirmDeleteTitle: 'Delete Invoice?',
      invoiceConfirmDeleteDesc: 'Are you sure you want to delete this invoice? This action cannot be undone.',

      // User Management
      userManagement: 'User Management',
      userList: 'User List',
      addStaff: 'Add Staff',
      bulkDelete: 'Bulk Delete',
      myProfile: 'My Profile',
      userSearchPlaceholder: 'Search user',
      filterAllRoles: 'All roles',
      selectRole: 'Select role',
      roleAdmin: 'Administrator',
      roleStaff: 'Staff',
      roleUser: 'Customer',
      colId: 'ID',
      colUsername: 'Username',
      colEmail: 'Email',
      colName: 'Full Name',
      colPhone: 'Phone Number',
      colPoint: 'Point',
      colRole: 'Role',
      colAddress: 'Address',
      colActions: 'Actions',
      actionViewDetail: 'View Details',
      actionDelete: 'Delete',
      actionEdit: 'Edit',
      confirmDeleteUserTitle: 'Delete User?',
      confirmDeleteUserDesc: 'Are you sure you want to delete this user? This action cannot be undone.',
      confirmBulkDeleteUserTitle: 'Bulk Delete Users?',
      confirmBulkDeleteUserDesc: 'Are you sure you want to delete the selected users? This action cannot be undone.',
      userDetailTitle: 'User Details',
      staffCreateTitle: 'Create Staff Account',
      staffCreateDesc: 'Enter information to create a new staff account on the system.',
      userFormUsername: 'Username',
      userFormEmail: 'Email',
      userFormName: 'Full Name',
      userFormPhone: 'Phone Number',
      userFormPassword: 'Password',
      userFormBirthDate: 'Birth Date',
      userFormGender: 'Gender',
      userFormPoint: 'Reward Points',
      userFormSave: 'Create Account',
      myProfileTitle: 'My Profile',
      myProfileDesc: 'Update your personal information.',
      myProfileAvatar: 'Avatar',
      myProfileUpdate: 'Update Profile',
      noUsersFound: 'No users found.',
      userDeletedSuccess: 'User successfully deleted',
      userBulkDeletedSuccess: 'Users successfully bulk deleted',
      staffCreatedSuccess: 'Staff account successfully created',
      profileUpdatedSuccess: 'Profile successfully updated',
      notifications: 'Notifications',
      allNotifications: 'All Notifications',
      markAllRead: 'Mark all as read',
      noNotifications: 'No notifications available',
      allNotificationsRead: 'All notifications have been read',
      staffOnlyFeature: 'This feature is only for staff and managers',
      confirmDeactivateExpired: 'Are you sure you want to deactivate expired showtimes?',
      errorOccurred: 'An error occurred: ',
      movieInfoNotFoundToDeleteShowtime: 'Movie information not found to delete showtime. Please try again later.',
      deleteError: 'Delete error: ',
      seatsRefreshedSuccess: 'Successfully refreshed selected seats!',
      seatsRefreshError: 'Error refreshing seats: ',
      unknownError: 'Unknown error',
      unableToExportExcel: 'Unable to export Excel. Please try again.',
      invoiceUpdatedSuccessMock: 'Updated successfully! (Local data is not refreshed because of using mock)',
      invoiceCreatedSuccess: 'Invoice created successfully! Code: ',
      invoiceCancelledSuccess: 'Invoice cancelled successfully',
      errorPrefix: 'Error: ',
      cannotCancel: 'Cannot cancel',
      invoiceDeletedSuccess: 'Invoice deleted successfully',
      cannotDelete: 'Cannot delete',
      paymentSuccessPrefix: 'Payment successful: ',
      errorCreatingVNPayUrl: 'Error creating VNPay payment URL',

      validation: {
        required: 'This field is required',
        minLength: 'Minimum {{min}} characters required',
        maxLength: 'Maximum {{max}} characters allowed',
        invalidUrl: 'Invalid URL'
      },
      promotionFood: 'Food & Beverages',
      promotionTicket: 'Ticket',
      rankStandard: 'Standard',
      rankVip: 'VIP',
      statusSuccess: 'Success',
      statusPending: 'Pending',
      statusFailure: 'Failure',
      statusExpired: 'Expired',
      statusPaid: 'Paid',
      statusHold: 'Hold',
      statusCancelled: 'Cancelled',
      statusEnded: 'Ended',
      statusNowShowing: 'Now Showing',
      statusComingSoon: 'Coming Soon',

      // Revenue Report
      revenueReport: 'Revenue Report',
      revenueSubtitle: 'Analyze revenue by time, cinema and movie',
      revenueFromDate: 'From Date',
      revenueToDate: 'To Date',
      revenueGroupBy: 'Group By',
      revenueGroupByDay: 'Day',
      revenueGroupByWeek: 'Week',
      revenueGroupByMonth: 'Month',
      revenueCinema: 'Cinema',
      revenueAllCinemas: 'All cinemas',
      revenueSelectCinema: 'Select cinema',
      revenueMovie: 'Movie',
      revenueAllMovies: 'All movies',
      revenueSelectMovie: 'Select movie',
      revenueSearch: 'Search',
      revenueSearching: 'Loading...',
      revenueExport: 'Export Excel',
      revenueExporting: 'Exporting...',
      revenueTotalRevenue: 'Total Revenue',
      revenueTicketRevenue: 'Ticket Revenue',
      revenueFoodRevenue: 'F&B Revenue',
      revenueTicketCount: 'Tickets Sold',
      revenueChartTitle: 'Revenue Chart',
      revenueChartArea: 'Area',
      revenueChartBar: 'Bar',
      revenueTableTitle: 'Revenue Details',
      revenueColPeriod: 'Period',
      revenueColTotal: 'Total Revenue',
      revenueColTicket: 'Ticket Revenue',
      revenueColFood: 'F&B Revenue',
      revenueColTicketCount: 'Tickets',
      revenueTableFooter: 'Total',
      revenueNoData: 'No data available',
      revenueNoDataDesc: 'Please select a date range and click Search',
      revenueError: 'Unable to load data',
      revenueErrorDesc: 'An error occurred while connecting to the server',
      revenueNoTableData: 'No data to display',
      revenuePeriods: 'periods',

      // Added showtime keys
      scheduleTitle: 'Showtimes Management',
      scheduleSearchPlaceholder: 'Search by name/code...',
      deactivateExpiredBtn: 'Deactivate Expired Showtimes',
      addShowtimeBtn: 'Add Showtime',
      showtimeListTitle: 'Showtimes List',
      noShowtimesFound: 'No showtimes found',
      theaterAndRoomInfo: 'Cinema & Room Info',
      theaterLabel: 'Cinema',
      roomLabel: 'Room',
      formatLabel: 'Format',
      showtimeTime: 'Showtime Time',
      showtimeDate: 'Showtime Date',
      startTime: 'Start Time',
      endTime: 'End Time',
      editShowtimeTitle: 'Edit Showtime',
      addShowtimeTitle: 'Add New Showtime',
      deleteShowtimeTitle: 'Delete Showtime?',
      deleteShowtimeConfirm: 'Are you sure you want to delete this showtime? This action cannot be undone.',
      scheduleCreateBtn: 'Create Showtime',

      // Added cinema keys
      roomsLabel: 'room(s)',
      editCinemaTitle: 'Edit Cinema',
      cinemaCodeAutoGenerated: 'Cinema code is automatically generated by the system.',
      roomCode: 'Room Code',
      editRoomTitle: 'Edit Room',
      deleteCinemaTitle: 'Delete Cinema?',
      deleteRoomTitle: 'Delete Room?',

      // Added movie keys
      movieSearchPlaceholder: 'Search movies...',
      movieListTitle: 'Movies List',
      noMoviesFound: 'No movies found.',
      movieCodeReadOnly: 'Movie Code (Read-only)',
      movieGeneralInfo: 'General Information',
      movieCastFormat: 'Cast & Format',
      movieContent: 'Description',
      paginationPage: 'Page',

      // Added promotion keys
      addPromotion: 'Add Promotion',
      addPromotionTitle: 'Add New Promotion',
      colPromoProgram: 'Program',
      colPromoDiscount: 'Discount',
      colPromoQuantity: 'Quantity',
      colPromoPeriod: 'Validity Period',
      colPromoTarget: 'Target Customers',
      colPromoStatus: 'Status',
      colPromoActions: 'Actions',
      noPromotionsFound: 'No promotions found',
      promoStatusRunning: 'Running',
      promoStatusEnded: 'Ended',
      promoFormName: 'Promotion Name',
      promoFormType: 'Promotion Type',
      promoFormDiscount: 'Discount Percentage (%)',
      promoFormQuantity: 'Quantity of Codes',
      promoFormRank: 'Customer Rank',
      promoFormStart: 'Start Date',
      promoFormEnd: 'End Date',
      promoFormDesc: 'Program Description',
      promoFormDescPlaceholder: 'Brief description of the promotion...',
      promoCreateBtn: 'Create Code Now',
      promoDeleteConfirmTitle: 'Delete Promotion?',
      promoDeleteConfirmDesc: 'Are you sure you want to delete this promotion? This code will no longer be valid.',
      promoDeleteBtn: 'Delete Now',

      // Added event keys
      addEvent: 'Add Event',
      addEventTitle: 'Add New Event',
      noEventsFound: 'No events found',
      eventStatusActive: 'Active',
      eventStatusEnded: 'Ended',
      eventFormImage: 'Event Image',
      eventFormImageHint: 'Click to upload event image',
      eventFormName: 'Event Name',
      eventFormNamePlaceholder: 'Enter event name...',
      eventSaveBtn: 'Save Event',
      eventDeleteConfirmTitle: 'Delete Event?',
      eventDeleteConfirmDesc: 'Are you sure you want to delete this event? This action cannot be undone.',

      // Added banner keys
      addBanner: 'Add Banner',
      addBannerTitle: 'Add New Banner',
      noBannersFound: 'No banners found',
      bannerFormImage: 'Banner Image (Recommended 21:9 aspect ratio)',
      bannerFormImageHint: 'Click to upload banner',
      bannerFormTitleVi: 'Title (Vietnamese)',
      bannerFormTitleEn: 'Title (English)',
      bannerSaveBtn: 'Save Banner',
      bannerDeleteConfirmTitle: 'Delete Banner?',
      bannerDeleteConfirmDesc: 'Are you sure you want to delete this banner? This action cannot be undone.',

      // Added setting keys
      settingsTitle: 'System Settings',
      operatingRules: 'Operating Rules',
      openTime: 'Opening Time',
      businessHours: 'Operating Hours',
      closeTime: 'Closing Time',
      closeTimeTooltip: 'Automatic lock feature when operating hours end.',
      breakTime: 'Break time between showtimes (minutes)',
      weekendPercent: 'Weekend surcharge (%)',
      timeBeginToChange: 'Lock time for showtime changes before showtime (minutes)',
      saveRules: 'Save Rules',
      updateRules: 'Update Rules',
      resetForm: 'Reset',
      historyTitle: 'Rule Change History',
      records: 'records',
      fetchingRecords: 'Loading records...',
      noRecords: 'No records found',
      colOpenTime: 'Opening Time',
      colOperatingHours: 'Operating Hours',
      colCloseTime: 'Closing Time',
      colBreakTime: 'Break Time',
      colWeekendSurcharge: 'Weekend Surcharge',
      colLockChangeTime: 'Lock Change Time',
      unitHour: 'hour(s)',
      unitMinute: 'minute(s)',
      editBtn: 'Edit',
      deleteBtn: 'Delete',
      toastSaveSuccess: 'Rules saved successfully',
      toastSaveError: 'Error saving rules',
      toastUpdateSuccess: 'Rules updated successfully',
      toastUpdateError: 'Error updating rules',
      toastDeleteSuccess: 'Rule deleted successfully',
      toastDeleteError: 'Error deleting rule',
      validationBreakTimeRequired: 'Break time is required.',
      validationBreakTimeNegative: 'Break time cannot be negative.',
      validationBreakTimeTooLong: 'Break time cannot exceed 120 minutes.',
      validationOpenHoursRange: 'Operating hours must be between 1 and 24 hours.',
      validationOpenTimeRequired: 'Opening time is required.',
      validationSurchargeRange: 'Weekend surcharge must be between 0% and 100%.',
      settingsDeleteTitle: 'Delete configuration?',
      settingsDeleteConfirm: 'Are you sure you want to delete this configuration? Cinema history may be affected.',

      // Added generic notification and seat extra keys
      loadingGeneric: 'Loading...',
      seatRefreshNote: 'Note: Only refresh when seat status is frozen/hung'
    },
    movies: {
      title: 'CineGo Movies',
      description: 'List of now-playing and coming-soon movies.',
      genre: 'Genre',
      duration: 'Duration',
      releaseDate: 'Release Date',
      director: 'Director',
      actor: 'Cast',
      language: 'Language',
      rated: 'Rated',
      contentTitle: 'Movie Details',
      showing: 'Now Showing',
      coming: 'Coming Soon',
      minutes: 'minutes',
      preBook: 'PRE-BOOK',
      notFound: 'Movie information not found.',
      goBack: 'Go Back',
      noShowing: 'No information about movies currently showing',
      noComing: 'No information about upcoming movies'
    },
    booking: {
      title: 'CineGo Booking',
      description: 'Choose screening, seats, and pay quickly.',
      chooseDate: 'Select Date',
      chooseCity: 'All Cities',
      chooseCinema: 'All Cinemas',
      noShowtimes: 'Sorry, no showtimes available for this date, please choose another day.',
      selectShowtime: 'Please select a date to view showtimes.',
      loadingSchedule: 'Loading information...',
      cityHcm: 'Ho Chi Minh',
      cityHn: 'Ha Noi',
      cityDn: 'Da Nang',
      roomStandard: '2D Subtitles',
      roomImax: 'IMAX 2D Subtitles',
      cinemaLabel: 'Cinema',
      personSeat: 'Person / Seat',
      screen: 'SCREEN',
      legendSelected: 'Selected',
      legendBooked: 'Booked',
      legendUnavailable: 'Unavailable',
      legendStandard: 'Standard',
      legendVip: 'VIP',
      legendSweetbox: 'Sweet Box',
      showtime: 'Showtime',
      roomLabel: 'Room',
      movieLabel: 'Movie',
      seatLabel: 'Seat',
      totalLabel: 'Total',
      selectSameSeatType: 'Please select seats of the same type',
      maxSeatsLimit: 'You can only select up to 8 seats.',
      seatGapWarning: 'Please do not leave a single empty seat to the left or right of your selected seats.',
      holdSeatsError: 'Error holding seats',
      holdSeatsConnectionError: 'Connection error while holding seats',
      cannotRetrievePaymentLink: 'Could not retrieve payment link',
      paymentProcessingError: 'Payment processing error',
      seatHoldExpired: 'Seat holding time has expired. Please select seats again'
    },
    shared: {
      loading: 'Loading',
      website: 'Website',
      close: 'Close',
      pleaseSelect: 'Please select...',
      noData: 'No data'
    },
    auth: {
      loginTab: 'Login',
      registerTab: 'Register',
      username: 'Username',
      password: 'Password',
      emailOrPhone: 'Username',
      captchaPrompt: 'Please enter the characters below *',
      captchaInput: 'Enter captcha',
      loadingCaptcha: 'Loading captcha...',
      noCaptcha: 'No captcha',
      forgotPassword: 'Forgot your password?',
      loginButton: 'LOGIN',
      registerButton: 'REGISTER',
      name: 'Name',
      phoneNumber: 'Phone number',
      email: 'Email',
      birthDate: 'Birth date',
      gender: 'Gender',
      day: 'Day',
      month: 'Month',
      year: 'Year',
      male: 'Male',
      female: 'Female',
      termsTitle: 'Registration terms',
      terms1: 'By clicking “Register” below, I agree to allow CG Vietnam to process my personal data according to the purpose disclosed in',
      terms2: 'The personal information provided here is accurate and matches my ID/CCCD/Passport and/or birth certificate. The email provided here is accurate and under my sole control.',
      terms3: 'I confirm the email and birth date match the information on my ID/CCCD. If they do not match, these details may not be updated and I may not receive',
      terms4: 'I agree to the',
      privacyPolicy: 'Privacy Policy',
      memberBenefits: 'member benefits',
      termsOfUse: 'CG Terms of Use',
      requiredName: 'Please enter your name',
      requiredUsername: 'Please enter a username',
      requiredPhone: 'Please enter your phone number',
      requiredEmail: 'Please enter your email',
      invalidEmail: 'Invalid email',
      requiredPassword: 'Password must be at least 6 characters',
      requiredBirthDate: 'Please choose a birth date',
      requiredGender: 'Please choose a gender',
      requiredCaptcha: 'Captcha is required',
      usernameLengthError: 'Username must be 3-20 characters.',
      nameLengthError: 'Full name must be 3-20 characters.',
      phoneLengthError: 'Phone number must start with 0 and have 10 digits.',
      passwordComplexError: 'Password must be 8-20 characters, with uppercase, lowercase, numbers and special characters.',
      captchaRequiredError: 'Please enter captcha.',
      consentPrompt: 'Please check the information confirmations and agree to the CG Terms of Use',
      consentLine: 'You must check this line to continue.',
      registerSuccess: 'Registration successful. Please log in.',
      loginSuccessPrefix: 'Login successful, welcome ',
      loginSuccess: 'Login successful',
      loginError: 'Login failed',
      registerError: 'Registration failed',
      captchaError: 'Unable to load captcha',
      captchaReload: 'Please reload the captcha.',
      staffOnly: 'Only staff and managers are allowed to log in here',
      staffMode: 'For Staff',
      forgotPasswordTitle: 'Forgot Password',
      resetPasswordTitle: 'Reset Password',
      otpLabel: 'OTP Code',
      newPassword: 'New Password',
      confirmNewPassword: 'Confirm New Password',
      otpSentMessage: 'OTP code has been sent to your email. If not found, please check your spam or trash folder.',
      forgotPasswordButton: 'SUBMIT REQUEST',
      resetPasswordButton: 'CHANGE PASSWORD',
      backToLogin: 'Back to Login',
      forgotPasswordError: 'Unable to send password recovery request',
      resetPasswordError: 'Password reset failed',
      passwordMismatch: 'Confirm password does not match',
      resetPasswordSuccess: 'Password changed successfully. Please login again.',
      requiredOtp: 'OTP is required'
    },
    account: {
      title: 'Account information',
      memberStatus: 'CineGo member',
      myTickets: 'My tickets',
      overviewTitle: 'General information',
      usernameLabel: 'Username',
      loginStateLabel: 'Status',
      loggedIn: 'Logged in',
      quickActionLabel: 'Quick action',
      quickActionValue: 'View account and manage logout',
      sidebarTitle: 'CineGo Account',
      infoGeneral: 'General Information',
      details: 'Account Details',
      paymentSettings: 'Payment Settings',
      memberCard: 'Member Card',
      rewardPoints: 'Reward Points',
      giftCards: 'Gift Cards',
      voucher: 'Voucher',
      coupon: 'Coupon',
      history: 'Transaction History',
      hello: 'Hello',
      manageIntro: 'With this page, you can manage all your account information.',
      tierLabel: 'Card Tier',
      totalSpend: 'Total Spending',
      cgvPoints: 'CineGo Points',
      giftCardLabel: 'Gift card',
      view: 'View',
      contactInfo: 'Account Information',
      contactHeader: 'CONTACT',
      change: 'Change',
      cropAvatarTitle: 'Crop Avatar Image',
      apply: 'Apply',
      cancel: 'Cancel',
      nameLabel: 'Name :',
      emailLabel: 'Email :',
      phoneLabel: 'Phone :',
      devMessage: 'Feature under development. Please come back later!',
      movieName: 'MOVIE',
      photoTicket: 'PHOTOTICKET',
      onlineStore: 'ONLINE STORE',
      egift: 'CINEGO EGIFT',
      productsCount: '{{count}} Product(s)',
      displayLabel: 'DISPLAY:',
      bookingCode: 'Booking Code :',
      statusLabel: 'Status :',
      statusCompleted: 'Completed',
      fromLabel: 'From',
      toLabel: 'To',
      totalAmount: 'VND',
      changeInfoTitle: 'CHANGE INFORMATION',
      cityLabel: 'City/Province',
      districtLabel: 'District',
      addressLabel: 'Address',
      oldPasswordLabel: 'Old Password',
      changePasswordToggle: 'I want to change password',
      optionalInfoTitle: 'Optional Information',
      cardNumberLabel: 'Member card number',
      favTheaterLabel: 'Favorite cinema',
      saveButton: 'SAVE',
      requiredHint: '* Required information',
      errorUpdatingPassword: 'Error updating password',
      newPasswordMismatch: 'New password and confirm password do not match',
      couponManageTitle: 'Coupon Management',
      couponRegisterTitle: 'Register Coupon',
      couponCodeLabel: 'Coupon Number',
      registerBtn: 'REGISTER',
      myCouponsTitle: 'Your Coupons',
      quickSearch: 'Quick search',
      oneWeek: '1 Week',
      oneMonth: '1 Month',
      threeMonths: '3 Months',
      searchBtn: 'Search',
      movieNameBtn: 'Movie Name',
      popcornDrinkBtn: 'Popcorn & Drink',
      allOption: 'All',
      unusedOption: 'Unused',
      usedOption: 'Used',
      expiredOption: 'Expired',
      colCoupon: 'Coupon',
      colCouponCode: 'Coupon Number',
      colRegDate: 'Registration date',
      colExpDate: 'Expiry date',
      colStatus: 'Status',
      badgeTicket: 'Ticket',
      badgeFnB: 'F&B',
      noCouponData: 'No coupon data matching the filter was found.'
    },
    titles: {
      home: 'CineGo Cinemas Vietnam',
      login: 'Login',
      register: 'Register Account',
      movieDetail: 'Movie Details',
      bookingTicket: 'Buy Tickets',
      bookingCorn: 'Concessions',
      bookingPayment: 'Payment',
      moviesShowing: 'Now Showing',
      moviesComing: 'Coming Soon',
      forgotpassword: 'Forgot Password',
      changepassword: 'Reset Password'
    },
    chatbot: {
      assistant: 'CineGo Assistant',
      online: 'Online',
      placeholder: 'Type your message here...',
      welcome: 'Hello! I am CineGo Assistant. How can I help you today?',
      promoLabel: '🎁 Promotions',
      faqLabel: '💡 FAQ & Support',
      faqIntro: 'You can find answers to frequently asked questions here:',
      promoQuery: 'What promotions are currently available?',
      systemError: "I haven't received a response from the system.",
      networkError: 'An error occurred connecting to the chatbot server. Please try again later!',
      refundPolicyLabel: 'Refund Policy',
      refundPolicyDesc: 'CineGo supports ticket refund/cancellation at least 60 minutes before showtime. The refunded amount will be transferred to your member reward points or your original payment method.',
      paymentMethodsLabel: 'Payment Methods',
      paymentMethodsDesc: 'We support various payment methods: International cards (Visa/Mastercard), popular e-wallets (Momo, ZaloPay, ShopeePay), VNPAY payment gateway, and bank transfers.',
      membershipLabel: 'Membership Benefits',
      membershipDesc: 'CineGo members enjoy special privileges: 5-10% reward points accumulation per transaction, free ticket/concession redemption, birthday tickets, and exclusive offers for early screenings.',
      locationsLabel: 'Cinema Locations',
      locationsDesc: "CineGo theaters are located in prime spots across HCMC, Hanoi, and Da Nang. You can view the detailed address list in the 'Theaters' section on the main menu of our website!",
      bookNow: 'Book Now',
      bookingId: 'BOOKING ID',
      confirmed: 'Confirmed'
    }
  }
} as const;

export type TranslationKey = keyof typeof translations.vi.auth | keyof typeof translations.vi.header;

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private readonly language = signal<AppLanguage>(this.readLanguage());

  readonly currentLanguage = computed(() => this.language());

  constructor() {
    this.applyLanguage(this.language());
  }

  useLanguage(language: AppLanguage): void {
    if (this.language() === language) return;
    this.language.set(language);
    this.persistLanguage(language);
    this.applyLanguage(language);
    if (typeof window !== 'undefined') {
      window.location.reload();
    }
  }

  isActive(language: AppLanguage): boolean {
    return this.language() === language;
  }

  t(key: string): string {
    const language = this.language();
    const group = key.startsWith('header.')
      ? 'header'
      : key.startsWith('footer.')
        ? 'footer'
        : key.startsWith('home.')
          ? 'home'
          : key.startsWith('admin.')
            ? 'admin'
            : key.startsWith('management.')
              ? 'management'
              : key.startsWith('movies.')
                ? 'movies'
                : key.startsWith('booking.')
                  ? 'booking'
                  : key.startsWith('shared.')
                    ? 'shared'
                    : key.startsWith('account.')
                      ? 'account'
                      : key.startsWith('titles.')
                        ? 'titles'
                        : key.startsWith('chatbot.')
                          ? 'chatbot'
                          : 'auth';
    const normalizedKey = key.replace(/^header\.|^footer\.|^home\.|^admin\.|^management\.|^movies\.|^booking\.|^shared\.|^auth\.|^account\.|^titles\.|^chatbot\./, '');
    const currentTranslations = translations[language][group] as Record<string, string>;
    return currentTranslations[normalizedKey] ?? key;
  }

  translateCity(city: string | undefined): string {
    if (!city) return '';
    const trimmed = city.trim();
    if (trimmed === 'Hà Nội') return this.t('booking.cityHn');
    if (trimmed === 'Hồ Chí Minh') return this.t('booking.cityHcm');
    if (trimmed === 'Đà Nẵng') return this.t('booking.cityDn');
    return city;
  }

  private readLanguage(): AppLanguage {
    if (typeof localStorage === 'undefined') {
      return 'vi';
    }

    const storedLanguage = localStorage.getItem(STORAGE_KEY);
    return storedLanguage === 'en' ? 'en' : 'vi';
  }

  private persistLanguage(language: AppLanguage): void {
    if (typeof localStorage === 'undefined') {
      return;
    }

    localStorage.setItem(STORAGE_KEY, language);
  }

  private applyLanguage(language: AppLanguage): void {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language;
    }
  }
}
